name: Docker-Ladder

on:
  push:
    branches: [ "main" ]

jobs:

  Build-verification:

    name: Build Docker ImageImage Check
    run-on: ubuntu-latest

  steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build . -t final-boss
       



    