name: Docker-Ladder CI

on:
  push:
    branches: [ "main" ]

jobs:
 
  build-verification:

    name: Build Docker Image Check
    runs-on: ubuntu-latest

    steps:
 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . -t final-boss